# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('zoom', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('show_home', models.BooleanField()),
                ('show_condom', models.BooleanField()),
                ('show_map_home', models.BooleanField()),
                ('show_map_condom', models.BooleanField()),
                ('show_collection', models.BooleanField()),
                ('registration_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
            },
        ),
    ]
